config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flights, :bookings, :passengers
  root 'flights#index'
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, foreign_key: 'start_id', class_name: 'Flight'
    has_many :arriving_flights, foreign_key: 'finish_id', class_name: 'Flight'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :flight
    has_many :passengers
    accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :to_airport, class_name: 'Airport', foreign_key: 'finish_id'
    belongs_to :from_airport, class_name: 'Airport', foreign_key: 'start_id'
    has_many :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
    belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def new
        @booking = Booking.new
        @flight = Flight.find(selection_params[:flight_id])
        @tickets = selection_params[:tickets]
        @tickets.to_i.times { @booking.passengers.build }
    end

    def create
        @booking = Booking.create(booking_params)
        booking_params[:passengers_attributes].each do |id, details|
            Passenger.create(details)
        end
        @booking.passengers.each do |passenger|
            PassengerMailer.with(passenger: passenger).confirmation_email.deliver_later
        end
        redirect_to booking_path(@booking.id)
    end

    def show
        @booking = Booking.find(params[:id])
    end

    private

    def booking_params
        params.require(:booking).permit(:id, :flight_id, :tickets, :passengers_attributes => [:name, :email])
    end

    def selection_params
        params.permit(:flight_id, :tickets)
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
    def index
        @airport_options = Airport.all.map { |a| [a.code, a.id] }
        @passenger_options = (1..4).to_a.map { |num| [num.to_s, num]}
        date_options = Flight.all.map { |d| [d.start_time.strftime("%d/%m/%Y"), d.start_time.strftime("%d/%m/%Y")] }
        @date_options = date_options.uniq
        if flight_params.has_key?(:date)
            @flights = Flight.where(
                start_id: flight_params[:from_code], 
                finish_id: flight_params[:to_code], 
                start_time: DateTime.strptime(flight_params[:date], '%d/%m/%Y').beginning_of_day..DateTime.strptime(flight_params[:date], '%d/%m/%Y').end_of_day
            )
        else
            @flights = Flight.all
        end
    end

    private

    def flight_params
        params.permit(:to_code, :from_code, :num_tickets, :date, :commit, :utf8)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<%= form_with model: @booking, local: true do |f| %>
    <%= 'Selected Flight:'%><br><br>
    <%= 'FROM: ' %><%= @flight.from_airport.code %><br>
    <%= 'TO: ' %><%= @flight.to_airport.code %><br>
    <%= 'DATE: ' %><%= @flight.start_time.strftime("%d/%m/%Y") %><br>
    <%= 'TIME: ' %><%= @flight.start_time.strftime('%H:%M') %><br>
    <%= 'DURATION: ' %><%= @flight.duration %><br><br><br>
    <div>Please Enter Passenger Details:</div><br>
    <%= f.fields_for :passengers do |passengers_form| %>
        <%= passengers_form.label :name, 'Name: '%>
        <%= passengers_form.text_field :name %><br>
        <%= passengers_form.label :email, 'Email: '%>
        <%= passengers_form.text_field :email %><br><br>
    <% end %>
    <%= f.hidden_field 'flight_id', :value => @flight.id %>
    <%= f.hidden_field 'tickets', :value => @tickets.to_i %>
    <%= f.submit 'Submit Booking' %>
<% end %>

app/views/bookings/show.html.erb
<div>Your booking: </div><br>
<%= 'FROM: ' %><%= @booking.flight.from_airport.code %><br>
<%= 'TO: ' %><%= @booking.flight.to_airport.code %><br>
<%= 'DATE: ' %><%= @booking.flight.start_time.strftime("%d/%m/%Y") %><br>
<%= 'TIME: ' %><%= @booking.flight.start_time.strftime('%H:%M') %><br>
<%= 'DURATION: ' %><%= @booking.flight.duration %><br><br><br>

<div>Passenger Details:</div><br>
<% @booking.passengers.all.each do |passenger| %>
    <%= 'NAME: ' %><%= passenger.name %><br>
    <%= 'EMAIL: ' %><%= passenger.email %><br><br>
<% end %>

app/views/flights/_result.html.erb
<%= form_with url: new_booking_path, method: 'get', local: true do |f| %>
    <% @flights.each do |flight| %>
        <%= 'FROM: ' %><%= flight.from_airport.code %><br>
        <%= 'TO: ' %><%= flight.to_airport.code %><br>
        <%= 'DATE: ' %><%= flight.start_time.strftime("%d/%m/%Y") %><br>
        <%= 'TIME: ' %><%= flight.start_time.strftime('%H:%M') %><br>
        <%= 'DURATION: ' %><%= flight.duration %><br>
        <%= 'SELECT ' %><%= f.radio_button :flight_id, flight.id %><br><br>
    <% end %>
    <%= f.hidden_field 'tickets', :value => params[:num_tickets] %>
    <%= f.submit 'Book' %>
<% end %>

app/views/flights/index.html.erb
<%= form_with(url: flights_path, method: "get", local: true) do %>
  <%= label_tag :from_code, 'FROM' %>
  <%= select_tag(:from_code, options_for_select(@airport_options)) %>
  <%= label_tag :to_code, 'TO' %>
  <%= select_tag(:to_code, options_for_select(@airport_options)) %>
  <%= label_tag :num_tickets, 'PEOPLE' %>
  <%= select_tag(:num_tickets, options_for_select(@passenger_options)) %>
  <%= label_tag :date, 'DATE' %>
  <%= select_tag(:date, options_for_select(@date_options)) %>
  <%= submit_tag 'Submit' %>
<% end %><br><br>

<% if @flights.present? %>
  <%= render 'result' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>